import { NextResponse } from 'next/server';
import nodemailer from 'nodemailer';

export async function POST(request: Request) {
  try {
    const body = await request.json();
    const { name, email, phone, interest, message } = body;

    // Validate required fields
    if (!name || !email || !interest || !message) {
      return NextResponse.json(
        { error: 'Missing required fields' },
        { status: 400 }
      );
    }

    // Configure the SMTP transport
    const transporter = nodemailer.createTransport({
      host: process.env.SMTP_HOST || 'smtp.gmail.com',
      port: Number(process.env.SMTP_PORT) || 465,
      secure: true, // true for 465, false for other ports
      auth: {
        user: process.env.SMTP_USER,
        pass: process.env.SMTP_PASS,
      },
    });



    const rawEmails = process.env.CONTACT_EMAIL || '';
    const emailList = rawEmails.split(',').map(e => e.trim()).filter(Boolean);
    const primaryEmail = emailList.length > 0 ? emailList[0] : process.env.SMTP_USER;
    const bccEmails = emailList.slice(1).join(', ');

    // Email content setup
    const mailOptions = {
      from: `"New Inquiry" <${process.env.SMTP_USER}>`, // Send via authenticated user to avoid spam filters
      to: primaryEmail,
      bcc: bccEmails,
      replyTo: email,
      subject: `New Inquiry via Safisha Nchi: ${interest}`,
      html: `
        <div style="font-family: 'Segoe UI', Arial, sans-serif; max-width: 600px; margin: 0 auto; background-color: #f8f7f3; padding: 20px; border-radius: 8px;">
          <div style="text-align: center; margin-bottom: 20px; padding: 20px 0; background-color: #0a3d2b; border-radius: 6px;">
            <h1 style="color: #ffffff; margin: 10px 0 0 0; font-size: 22px; font-weight: 600; letter-spacing: -0.02em;">Safisha Nchi</h1>
          </div>
          
          <div style="background-color: #ffffff; padding: 30px; border-radius: 6px; border-top: 4px solid #8ec63f; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
            <h2 style="color: #0a3d2b; font-size: 18px; margin-top: 0;">New Partnership Inquiry</h2>
            <p style="color: #555; line-height: 1.6; font-size: 15px;">You have received a new message from the Safisha Nchi contact form.</p>
            
            <table style="width: 100%; border-collapse: collapse; margin-top: 20px; font-size: 14px;">
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #777; width: 120px;"><strong>Name</strong></td>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #111;">${name}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #777;"><strong>Email</strong></td>
                <td style="padding: 10px; border-bottom: 1px solid #eee;"><a href="mailto:${email}" style="color: #0a3d2b; text-decoration: none;">${email}</a></td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #777;"><strong>Phone</strong></td>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #111;">${phone || 'Not provided'}</td>
              </tr>
              <tr>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #777;"><strong>Interest</strong></td>
                <td style="padding: 10px; border-bottom: 1px solid #eee; color: #111;">
                  <span style="background-color: #e6f4ea; color: #0a3d2b; padding: 4px 10px; border-radius: 20px; font-size: 13px; font-weight: 600;">
                    ${interest}
                  </span>
                </td>
              </tr>
            </table>
            
            <div style="margin-top: 25px;">
              <h3 style="color: #0a3d2b; font-size: 15px; margin-bottom: 10px;">Message:</h3>
              <p style="background: #fdfdfd; padding: 15px; border-radius: 5px; border: 1px solid #eaeaea; line-height: 1.7; color: #333; font-size: 14px;">
                ${message.replace(/\n/g, '<br />')}
              </p>
            </div>
          </div>
          
          <div style="text-align: center; margin-top: 25px; padding-top: 15px; border-top: 1px solid #e0dfd9;">
            <p style="font-size: 12px; color: #888; margin: 0;">This message was automatically generated by the Safisha Nchi website.</p>
            <p style="font-size: 12px; color: #888; margin: 5px 0 0 0;">&copy; ${new Date().getFullYear()} Safisha Nchi Ltd. All rights reserved.</p>
          </div>
        </div>
      `,
    };

    // Send the email
    await transporter.sendMail(mailOptions);

    return NextResponse.json(
      { message: 'Email sent successfully' },
      { status: 200 }
    );
  } catch (error) {
    console.error('Error sending email:', error);
    return NextResponse.json(
      { error: 'Failed to send email. Please try again later.' },
      { status: 500 }
    );
  }
}
